apiVersion: "application.responsive.dev/v1"
kind: "ResponsivePolicy"
metadata:
  name: example
  namespace: responsive
spec:
  applicationName: responsive-example
  status: POLICY_STATUS_MANAGED
  policyType: KAFKA_STREAMS
  kafkaStreamsPolicy:
    maxReplicas: 3
    diagnosers:
      - type: PROCESSING_RATE_SCALE_UP
        processingRateScaleUp:
          rate: 150
          windowMs: 15000
      - type: PROCESSING_RATE_SCALE_DOWN
        processingRateScaleDown:
          rate: 75
          windowMs: 15000

